version: '3.1'
services:
    db:
        image: mongo:latest
        container_name: MongoDB
        ports:
            - "27017:27017"
        volumes:
            - /data/db
        restart: always
    
    nuclei:
        image: projectdiscovery/nuclei:latest
        container_name: Nuclei
