services:
    db:
        image: mongo:latest
        container_name: MongoDB
        ports:
            - "27017:27017"
        volumes:
            - dbdata:/data/db
        restart: always
    

volumes:
    dbdata: