# Templates with tags to run
#tags: info

# Templates with tags to exclude
# exclude-tags: info

# Templates to scan
#templates:
#  - cves/
#  - vulnerabilities/
#  - misconfiguration/

# Templates to exclude scan
#exclude:
#  - vulnerabilities/xxx
#  - misconfiguration/xxxx

# Send random User-agent for each scan
random-agent: false

# Rate limit configuration for scan
rate-limit: 50
bulk-size: 50
concurrency: 50
